Zoom improvements
elementary/photos pull request #635
Opened 2021-08-27 15:00 UTC by jeremypw

- Increase possible range of zoom
 - Maintain fine zoom control by holding down `<Alt>` as well as `<Ctrl>`
 - Improve smoothness of scrolling by aggregating smooth scroll events and throttling scroll events
 - Update zoom slider and cursor outside of scroll handler
 - Correct interpolation function
 - Add tooltips to SliderAssembly
 - Use same tooltips in CollectionPage and EditingHostPage, lose custom tooltip property

Fixes #634 

Note that unmodified scrolling also works to zoom when hovering the zoom control (in master) but as this does not work otherwise it has been omitted from the tooltip.

Likewise fine zooming only works when hovering the image in EditingHostPage so has been omitted from the zoom control.

In both places the SliderAssembly is used, the tooltips are now similar to those used in the Code zoom control.  Files uses "zoom" to refer to thumbnail size.

2021-08-31 18:09 UTC, cassidyjames requested changes
One relatively minor thing noted, plus a question: is is possible to use GLib Actions throughout these shortcut tooltips instead of manually specifying the shortcuts in the tooltip copy?

2021-09-01 10:35 UTC, jeremypw commented
The existing code relating to actions and accelerators is rather involved :grimacing:  I'll see whether I can introduce a zoom actin

2021-09-01 10:51 UTC, jeremypw commented
@cassidyjames  Looks like the existing infrastructure for actions uses deprecated code like Gtk.ActionEntry and Gtk.UIManager.

2021-09-01 11:10 UTC, jeremypw commented on src/Widgets/SliderAssembly.vala
> +        var secondary_tooltip_text = _("Control + Scroll, Control + Plus, Control + Minus");
Done

2021-09-01 11:11 UTC, jeremypw commented
I think any refactoring to use actions would be too extensive for this PR.  Maybe the whole action infrastructure can be reviewed to remove deprecated code in another PR.

2021-09-02 06:18 UTC, cassidyjames approved these changes

2021-09-02 06:19 UTC, merged