Simplify StraightenToolWindow class
elementary/photos pull request #666
Opened 2021-11-12 06:10 UTC by ZenitsuDev

StraightenToolWindow has a base function which derives from EditingToolWindow, although the constructor of EditingToolWindow only sets transient_for property to the container, so transient_for can be called directly from StraightenToolWindow constructor itself without depending on the Parent Class (EditingToolWindow). The other functions included in the constructor are moved to the construct block to simplify further. Thanks @danrabbit

2021-11-12 18:28 UTC, danrabbit commented
@ZenitsuDev this looks good purely from a functional perspective! Nice simple fix.

The linter is complaining because there's some spaces introduced on line 124. Since this is a blank lane, it should be completely blank

2021-11-12 18:29 UTC, danrabbit requested changes
See above :point_up:

2021-11-13 00:12 UTC, ZenitsuDev commented
Greetings. I changed it. It should be fixed now :)

2021-11-13 02:18 UTC, danrabbit commented
@ZenitsuDev if you look at the "files changed" tab, you can see that you've now introduced a bunch of spaces on a bunch of other lines somehow :sweat_smile:

2021-11-13 03:27 UTC, ZenitsuDev commented
I'm sorry about that :) It should be fixed by now :)

2021-11-13 03:48 UTC, danrabbit approved these changes
Hey there we go. Looks good. Nice job!

2021-11-13 03:50 UTC, merged

2021-11-13 08:08 UTC, ZenitsuDev commented
thanks @danrabbit !